# Generated by Django 2.2 on 2019-05-27 22:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('index', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='index')),
                ('event_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='type')),
                ('event_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='eventTime')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data')),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='message')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Profile')),
                ('identity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='identity')),
                ('arc_state', models.NullBooleanField()),
                ('datawarehouse_sync', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('mail_title', models.CharField(max_length=256, null=True, verbose_name='Título')),
                ('mail_template', models.TextField(null=True, verbose_name='Template')),
                ('mail_partial', models.TextField(blank=True, null=True, verbose_name='Partial')),
                ('event_type', models.CharField(choices=[('benefits', 'Beneficios'), ('MAGIC_LINK_SEND', 'MAGIC_LINK_SEND'), ('PASSWORD_RESET', 'PASSWORD_RESET'), ('PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_REQUEST'), ('PROFILE_EDIT', 'PROFILE_EDIT'), ('SIGNUP_EDIT', 'SIGNUP_EDIT'), ('VERIFY_EMAIL', 'VERIFY_EMAIL')], max_length=64, verbose_name='Tipo')),
                ('partner_code', models.CharField(choices=[('elcomercio', 'Comercio'), ('gestion', 'Gestión')], max_length=64, verbose_name='Partner')),
            ],
            options={
                'verbose_name': '    Mail Template',
                'verbose_name_plural': '   Mail Templates',
            },
        ),
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('state', models.BooleanField(default=False, verbose_name='Enviado')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío')),
                ('email', models.CharField(max_length=256, null=True, verbose_name='email')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Config')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Response')),
                ('mail_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arcsubs.MailTemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': '    Send mail',
                'verbose_name_plural': '   Send mail',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('state_send', models.BooleanField(default=False, verbose_name='Send Mail')),
                ('log_index', models.BigIntegerField(blank=True, null=True)),
                ('log_uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('log_email', models.CharField(blank=True, max_length=128, null=True)),
                ('log_type', models.CharField(max_length=64, null=True, verbose_name='Tipo')),
                ('log_request', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request')),
                ('log_error', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request')),
                ('send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatedMailLogSend', to='arcsubs.SendMail', verbose_name='SendMail ID')),
            ],
            options={
                'verbose_name': 'Mail Log',
                'verbose_name_plural': 'Mails Logs',
            },
        ),
    ]
