# Generated by Django 2.2 on 2019-06-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0003_auto_20190605_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcuser',
            name='username',
        ),
        migrations.AddField(
            model_name='arcuser',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Type'),
        ),
    ]
