# Generated by Django 2.2 on 2019-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0004_auto_20190605_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain'),
        ),
    ]
