# Generated by Django 2.2 on 2019-06-28 14:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0006_arcuser_first_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='first_profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='First profile'),
        ),
    ]
