# Generated by Django 2.2 on 2019-06-27 15:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0007_auto_20190626_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='fist_login_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Datos del primer login'),
        ),
        migrations.AddField(
            model_name='arcuser',
            name='signup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='arcuser',
            name='signup_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Datos de registro'),
        ),
    ]
