# Generated by Django 2.2 on 2019-06-27 15:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0009_auto_20190627_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='identities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='identities'),
        ),
    ]
