# Generated by Django 2.2 on 2019-06-27 23:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0010_arcuser_identities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mppuser',
            options={'managed': False, 'verbose_name': 'Usuario de MPP', 'verbose_name_plural': 'Usuarios de MPP'},
        ),
        migrations.AlterModelOptions(
            name='mppuserlog',
            options={'managed': False, 'verbose_name': 'Reactivación de sesion', 'verbose_name_plural': 'Pasos de reactivación'},
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_identities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='1er identities'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='fist_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='1er login'),
        ),
    ]
