# Generated by Django 2.2 on 2019-06-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0011_auto_20190627_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcuser',
            old_name='fist_login',
            new_name='first_login',
        ),
        migrations.RenameField(
            model_name='arcuser',
            old_name='fist_login_data',
            new_name='first_login_data',
        ),
    ]
