# Generated by Django 2.2 on 2019-06-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0012_auto_20190627_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='origin_action',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acción para registro'),
        ),
    ]
