# Generated by Django 2.2 on 2019-06-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0013_arcuser_origin_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcuser',
            old_name='origin_action',
            new_name='first_login_action',
        ),
    ]
