# Generated by Django 2.2 on 2019-07-03 15:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0014_auto_20190627_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MppUser',
        ),
        migrations.DeleteModel(
            name='MppUserLog',
        ),
        migrations.RenameField(
            model_name='arcuser',
            old_name='signup_data',
            new_name='created_on_data',
        ),
        migrations.RemoveField(
            model_name='arcuser',
            name='datawarehouse_sync',
        ),
        migrations.RemoveField(
            model_name='arcuser',
            name='first_login_data',
        ),
        migrations.RemoveField(
            model_name='arcuser',
            name='signup',
        ),
        migrations.AddField(
            model_name='arcuser',
            name='created_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='arcuser',
            name='first_login_device',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dispositivo de login'),
        ),
        migrations.AddField(
            model_name='arcuser',
            name='first_login_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Método de login'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_identities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Primer identities con login'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primer login'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_login_action',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Acción para login'),
        ),
    ]
