# Generated by Django 2.2 on 2019-06-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0014_auto_20190627_2038'),
        ('arcsubs', '0007_auto_20190628_0955'),
    ]

    operations = [
    ]
