# Generated by Django 2.2 on 2019-07-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0015_merge_20190628_0956'),
        ('arcsubs', '0016_auto_20190703_1113'),
    ]

    operations = [
    ]
