# Generated by Django 2.2.3 on 2019-08-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0017_merge_20190703_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='first_site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primer portal'),
        ),
        migrations.AddField(
            model_name='arcuser',
            name='last_site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Último portal'),
        ),
    ]
