# Generated by Django 2.2.3 on 2019-08-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0017_merge_20190703_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='term_cond_pol_priv',
            field=models.NullBooleanField(verbose_name='Terminos y Condiciones y Politicas de Privacidad'),
        ),
    ]
