# Generated by Django 2.2.3 on 2019-08-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0018_arcuser_term_cond_pol_priv'),
        ('arcsubs', '0018_auto_20190801_1738'),
    ]

    operations = [
    ]
