# Generated by Django 2.2.3 on 2019-08-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0019_merge_20190805_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='term_cond_pol_priv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Terminos y Condiciones y Politicas de Privacidad'),
        ),
    ]
