# Generated by Django 2.2.3 on 2019-08-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0020_auto_20190805_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='pass_encript',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Portal'),
        ),
    ]
