# Generated by Django 2.2.3 on 2019-08-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0022_auto_20190828_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passarcuser',
            options={'verbose_name': 'Pass Usuario de ARC', 'verbose_name_plural': 'Pass Usuarios de ARC'},
        ),
    ]
