# Generated by Django 2.2.3 on 2019-08-29 01:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0023_auto_20190828_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('report_type', models.CharField(choices=[('sign-up-summary', 'Registros')], default='sign-up-summary', max_length=50, null=True, verbose_name='Tipo')),
                ('site', models.CharField(choices=[('elcomercio', 'El Comercio'), ('gestion', 'Gestión'), ('peru21', 'Perú21')], max_length=20, null=True, verbose_name='Portal')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Responce')),
                ('error', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Error')),
                ('data', models.FileField(blank=True, null=True, upload_to='', verbose_name='Reporte')),
                ('records', models.IntegerField(blank=True, null=True, verbose_name='Número de registros')),
                ('hits', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de intentos')),
                ('data_loaded', models.NullBooleanField(verbose_name='Datos cargados')),
            ],
            options={
                'verbose_name': 'Reporte',
            },
        ),
    ]
