# Generated by Django 2.2.3 on 2019-08-29 02:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0024_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True, verbose_name='Code')),
                ('event_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Message')),
                ('site', models.CharField(blank=True, max_length=20, null=True, verbose_name='Site')),
                ('timestamp', models.BigIntegerField(blank=True, null=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones de ARC',
            },
        ),
    ]
