# Generated by Django 2.2.3 on 2019-08-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0025_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes de ARC'},
        ),
    ]
