# Generated by Django 2.2.3 on 2019-12-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0026_auto_20190829_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arcuser',
            options={'ordering': ('-created_on', '-created'), 'verbose_name': 'Usuario de ARC', 'verbose_name_plural': '[ARC] Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': '[ARC] Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': '[ARC] Reportes'},
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='passarcuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='passarcuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='report',
            name='data_loaded',
            field=models.NullBooleanField(choices=[(None, 'Pendiente'), (True, 'Completa'), (False, 'Incompleta')], verbose_name='Carga de datos'),
        ),
        migrations.AlterField(
            model_name='report',
            name='site',
            field=models.CharField(choices=[('depor', 'Depor'), ('diariocorreo', 'Diario Correo'), ('elbocon', 'El Bocón'), ('elcomercio', 'El Comercio'), ('gestion', 'Gestión'), ('ojo', 'Ojo'), ('peru21', 'Perú21'), ('publimetro', 'Publimetro'), ('trome', 'Trome')], max_length=20, null=True, verbose_name='Portal'),
        ),
    ]
