# Generated by Django 2.2.3 on 2019-12-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0027_auto_20191223_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcuser',
            name='created_on_data',
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado'),
        ),
    ]
