# Generated by Django 2.2.9 on 2019-12-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0028_auto_20191223_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='created_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de registro en ARC'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primer Portal'),
        ),
    ]
