# Generated by Django 2.2.6 on 2020-01-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0029_auto_20191227_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='passarcuser',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Creado'),
        ),
    ]
