# Generated by Django 2.2.6 on 2020-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0030_auto_20200127_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='passarcuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
    ]
