# Generated by Django 2.2.9 on 2020-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0032_promotion_promotionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionuser',
            name='uuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='UUID'),
        ),
    ]
