# Generated by Django 3.0.1 on 2020-02-18 21:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0033_promotionuser_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcUserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Ultima fecha de modificacion')),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='ultima fecha de login')),
                ('created_on', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro en ARC')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site')),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='registro')),
            ],
            options={
                'verbose_name': '[Reporte] Usuario de ARC',
                'verbose_name_plural': '[Reporte] Usuarios',
                'ordering': ('-created_on', '-created'),
            },
        ),
        migrations.CreateModel(
            name='LogArcUserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('schedule_request', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='schedule request')),
                ('schedule_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='schedule response')),
                ('download_total', models.BigIntegerField(blank=True, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': '[Log] Reporte Usuario de ARC',
                'verbose_name_plural': '[Log] Reporte Usuarios',
            },
        ),
    ]
