# Generated by Django 2.2.9 on 2020-02-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0037_arcuserreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='domain',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Domain'),
        ),
    ]
