# Generated by Django 2.2.9 on 2020-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0038_auto_20200219_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuserreport',
            name='created_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de registro en ARC'),
        ),
        migrations.AlterField(
            model_name='arcuserreport',
            name='last_login_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ultima fecha de login'),
        ),
        migrations.AlterField(
            model_name='arcuserreport',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ultima fecha de modificacion'),
        ),
    ]
