# Generated by Django 2.2.9 on 2020-06-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0040_auto_20200221_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcUserDeletedProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Usuarios a eliminar',
                'verbose_name_plural': '[Report] Usuarios a eliminar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('arcsubs.arcuser',),
        ),
    ]
