# Generated by Django 2.2.9 on 2020-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0042_auto_20200625_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcuser',
            name='without_activity',
        ),
        migrations.AddField(
            model_name='arcuser',
            name='with_activity',
            field=models.NullBooleanField(default=False, verbose_name='Con actividad'),
        ),
    ]
