# Generated by Django 2.2.9 on 2020-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0043_auto_20200625_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='with_subscription',
            field=models.NullBooleanField(default=False, verbose_name='Con Suscripcion'),
        ),
    ]
