# Generated by Django 2.2.9 on 2020-07-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0044_arcuser_with_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcuser',
            name='first_login_action',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Acción para login'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_login_device',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dispositivo de login'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_login_method',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Método de login'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='first_site',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Primer Portal'),
        ),
        migrations.AlterField(
            model_name='arcuser',
            name='last_site',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Último portal'),
        ),
    ]
