# Generated by Django 2.2.9 on 2020-07-14 15:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0045_auto_20200708_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='token')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='arcuser',
            name='state_delete',
            field=models.CharField(blank=True, choices=[('R', 'Solicitud'), ('A', 'Aprobado')], max_length=64, null=True, verbose_name='Estado de la Eliminacion'),
        ),
        migrations.CreateModel(
            name='DeleteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('type_delete', models.CharField(blank=True, choices=[('R', 'Solicitud'), ('A', 'Aprobado')], max_length=64, null=True, verbose_name='Type')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data')),
                ('id_response', models.IntegerField(blank=True, null=True, verbose_name='Id Respuesta')),
                ('status', models.CharField(blank=True, max_length=80, null=True, verbose_name='estado')),
                ('arc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arcsubs.ArcUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario Eliminado',
                'verbose_name_plural': 'Usuarios Eliminados',
            },
        ),
    ]
