# Generated by Django 2.2.9 on 2020-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0046_auto_20200714_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuser',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='token'),
        ),
    ]
