# Generated by Django 2.2.9 on 2020-07-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0047_auto_20200714_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteuser',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='log'),
        ),
    ]
