# Generated by Django 2.2.9 on 2020-07-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0048_deleteuser_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteuser',
            name='type_delete',
            field=models.CharField(blank=True, choices=[('R', 'Solicitud'), ('A', 'Aprobar')], max_length=64, null=True, verbose_name='Type'),
        ),
    ]
