# Generated by Django 2.2.9 on 2020-07-15 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0049_auto_20200714_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data')),
                ('id_response', models.IntegerField(blank=True, null=True, verbose_name='Id Respuesta')),
                ('status', models.CharField(blank=True, max_length=80, null=True, verbose_name='estado')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log request')),
                ('arc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arcsubs.ArcUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario Eliminado',
                'verbose_name_plural': 'Usuarios Eliminados',
            },
        ),
        migrations.CreateModel(
            name='RequestDeleteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data')),
                ('id_response', models.IntegerField(blank=True, null=True, verbose_name='Id Respuesta')),
                ('status', models.CharField(blank=True, max_length=80, null=True, verbose_name='estado')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log')),
                ('arc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arcsubs.ArcUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Eliminacion',
                'verbose_name_plural': 'Solicitudes de Eliminacion',
            },
        ),
        migrations.DeleteModel(
            name='DeleteUser',
        ),
    ]
