# Generated by Django 2.2.9 on 2020-07-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0050_auto_20200715_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='arc_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deletedusers', to='arcsubs.ArcUser', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='requestdeleteuser',
            name='arc_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestdeletes', to='arcsubs.ArcUser', verbose_name='Usuario'),
        ),
    ]
