# Generated by Django 2.2.9 on 2020-07-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0051_auto_20200715_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcuser',
            name='state_delete',
        ),
    ]
