# Generated by Django 2.2.9 on 2020-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0052_remove_arcuser_state_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='email_verified',
            field=models.NullBooleanField(default=False, verbose_name='Email verificado'),
        ),
    ]
