# Generated by Django 2.2.9 on 2020-09-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0053_arcuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='date_verified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Verificacion de Email'),
        ),
    ]
