# Generated by Django 2.2.9 on 2021-05-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0055_arcuser_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcUserExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('data_treatment', models.CharField(blank=True, max_length=40, null=True, verbose_name='Autorización de datos')),
                ('arc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_extrafields', to='arcsubs.ArcUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Campos extra',
                'verbose_name_plural': 'Campos extra',
            },
        ),
    ]
