# Generated by Django 2.2.9 on 2021-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcsubs', '0056_arcuserextrafields'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ultimo login'),
        ),
    ]
