# Generated by Django 2.2 on 2019-07-15 21:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, null=True, unique=True, verbose_name='Email')),
                ('csv_profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('mpp_profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('arc_profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('UNKNOWN', 'Desconocido'), ('PENDING', 'Usuario inactivo'), ('IN_PROCESS', 'Contraseña pendiente'), ('MIGRATED', 'Migración completa')], default=None, max_length=128, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario de MPP',
                'verbose_name_plural': 'Usuarios de MPP',
                'managed': False,
                'db_table': 'ecoid_migrateuser',
            },
        ),
        migrations.CreateModel(
            name='MppUserStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_email', models.CharField(db_index=True, max_length=128, null=True, verbose_name='Email')),
                ('domain', models.CharField(max_length=128, null=True, verbose_name='Domain')),
                ('date_register', models.DateTimeField(blank=True, null=True, verbose_name='Date register')),
                ('date_edition', models.DateTimeField(blank=True, null=True, verbose_name='Date edition')),
                ('mpp_account_id', models.CharField(max_length=128, null=True, verbose_name='Mpp Account')),
                ('arc_account_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Arc Account')),
                ('type', models.CharField(max_length=32, null=True, verbose_name='Type')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ip', models.CharField(max_length=32, null=True, verbose_name='IP')),
                ('referer', models.CharField(max_length=350, null=True, verbose_name='Referer')),
                ('user_agent', models.CharField(max_length=350, null=True, verbose_name='User Agent')),
                ('origin_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Reactivación de sesion',
                'verbose_name_plural': 'Pasos de reactivación',
                'managed': False,
                'db_table': 'ecoid_usercredentials',
            },
        ),
        migrations.CreateModel(
            name='ArcReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('report_type', models.CharField(choices=[('sign-up-summary', 'Registros')], max_length=20, null=True)),
                ('json', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Procesado')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de los Usuarios Migrados de MPP',
            },
        ),
        migrations.CreateModel(
            name='UsersReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
            ],
        ),
    ]
