# Generated by Django 2.2 on 2019-07-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signwall', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UsersReport',
        # ),
    ]
