# Generated by Django 2.2 on 2019-07-16 01:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signwall', '0002_delete_usersreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
            ],
        ),
    ]
