# Generated by Django 2.2.3 on 2019-08-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signwall', '0003_usersreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreport',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Pendiente'),
        ),
    ]
