# Generated by Django 2.2.3 on 2019-08-29 00:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signwall', '0005_auto_20190828_1715'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ArcReport',
        # ),
        migrations.AddField(
            model_name='report',
            name='error',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sign-up-summary', 'Registros')], default='sign-up-summary', max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='site',
            field=models.CharField(choices=[('elcomercio', 'El Comercio'), ('gestion', 'Gestión'), ('peru21', 'Perú21')], max_length=20, null=True, verbose_name='Portal'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de inicio'),
        ),
    ]
