# Generated by Django 2.2.3 on 2019-08-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signwall', '0007_auto_20190828_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
