# Generated by Django 2.2.3 on 2019-08-29 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signwall', '0008_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassArcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('pass_encript', models.CharField(blank=True, max_length=20, null=True, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Pass Usuario de ARC',
                'verbose_name_plural': 'Pass Usuarios de ARC',
            },
        ),
    ]
